"""menambahkan slug

Revision ID: 7d0fad08f96e
Revises: 43fec86d50a9
Create Date: 2022-02-22 09:27:32.940821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d0fad08f96e'
down_revision = '43fec86d50a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog', sa.Column('slug', sa.String(length=250), nullable=False))
    op.create_unique_constraint(None, 'blog', ['slug'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'blog', type_='unique')
    op.drop_column('blog', 'slug')
    # ### end Alembic commands ###
